### ISSUE TITLE
ISDL_devのアカウントをteamsで使えるようにする

### ISSUE THREAD

**Issue by kabigon-1015** [ISDL-dev/ISDL-Sentinel#108]
# 目的/背景

- teamsbotを専用のアカウントで利用したい

# 前提条件

- なし

# 内容（やること）

- isdl_devをISDL_2024に招待して99_devチャネルに追加する

# 完了条件

- [ ] ISDL_2024のチームでBotが使える状態になっていること

# 参考情報

**Comment by hoka-isdl** [comment]
teamsのチャネルは毎年変わるのでurlも変わる
そのため，URLを再発行する手間は変わらない．
発信源はユーザにして，学生の誰かにする．
powerAutemate
