### ISSUE TITLE
【ユーザ認証】顔認証とWebAuthnの調査

### ISSUE THREAD

**Issue by kabigon-1015** [ISDL-dev/ISDL-Sentinel#20]
# 目的/背景

- 現状指紋認証デバイスの制約として、指紋を10本までしか登録できないため、研究室規模で使うには難しそうであることが分かった
- いかに入室処理を楽にして使ってもらうかが鍵になるので、顔認証+WebAuthnで入室処理ができるかどうかを調査したい

# 前提条件

- なし
 
# 内容（やること）

- 顔認証+WebAuthnの調査
 
# 完了条件

- [ ] 実現可能性を調査してグループチャットで報告する
- [ ] 顔認証デバイスの選定
- [ ] 小野先生へ購入依頼
 
# 参考情報
- 指紋認証デバイス一覧 https://my-best.com/5996
- WebAuthn概要 https://www.nri-secure.co.jp/blog/what-is-webauthn

**Comment by hoka-isdl** [comment]
@kabigon-1015 @akiya125 
# 調査結果
## WebAuthnについて
割と簡単に実装できそう．
Backendで実装することになる．
動作検証したところ，PCでもIphoneでも指紋認証およびFaceIDが使用できた．
ISDL-Sentinelに導入する場合，userテーブルにdisplaynameとcredentialsカラムを追加する必要がある．
また，sessionデータを保持するテーブルが新規に必要になる．

実装フローは以下の通り
```mermaid
sequenceDiagram
    actor User
    participant Browser
    participant Client
    participant Go Server
    participant DB
    User->>Client: パスキー登録ボタンを押す
    Client->>+Go Server: `/begin_create`にChallengeをリクエスト
    Go Server->>DB: セッションを保存
    Go Server->>Client: Challengeを返す
    Client->>Browser: パスキー登録リクエスト
    Browser->>+User: ユーザのクレデンシャルをもらう
    User-->>-Browser: パスキー登録
    Browser->>Client: クレデンシャルもらう
    Client->>Go Server: `/create`にクレデンシャル渡す
    DB->>Go Server: セッションもらう
    Go Server->>Go Server: 検証
    Go Server->>-Client: 成功
```

サンプルコード
- https://github.com/subkaitaku/webauthn-example/tree/main
- https://github.com/cateiru/go-webauthn-sample/tree/main
- https://github.com/hbolimovsky/webauthn-example/tree/master

## 顔認証について
API連携可能な顔認証デバイスは存在する．
ただ具体的にwebアプリと連携したような記事はないため実装には時間がかかりそう．
先にwebauthnを実装してから余裕がありそうであれば実装を検討しても面白いかも．

### API連携可能な顔認証デバイス

1. ZKTeco スタンドアロン型顔認証端末
   - 特徴：
     - 顔認証、指紋認証、カード認証に対応
     - ネットワーク接続可能（有線/無線LAN）
     - REST APIをサポート
     - 認証成功時にHTTPリクエストを送信可能
   - 価格帯：50,000円〜150,000円程度

2. Suprema FaceStation 2
   - 特徴：
     - 高速で正確な顔認識
     - マスク着用時の認識にも対応
     - BioStar 2プラットフォームを通じてAPIアクセス可能
     - カスタムイベント設定で認証成功時にAPIコールを実行可能
   - 価格帯：100,000円〜200,000円程度

3. Hikvision DS-K1T671系列
   - 特徴：
     - ディープラーニングアルゴリズムによる高精度認識
     - マスク検知機能付き
     - ISAPI（Hikvision独自のAPI）をサポート
     - イベントリンケージ機能でAPI連携可能
   - 価格帯：80,000円〜150,000円程度

4. Anviz FacePass 7 IRT
   - 特徴：
     - 顔認証と体温測定の組み合わせ
     - クラウドベースの管理システムと連携
     - REST APIを提供
     - Webhookを使用してイベント通知を送信可能
   - 価格帯：70,000円〜130,000円程度

**Comment by kabigon-1015** [comment]
@hoka-isdl 
調査おれもしてみましたが、顔認証は導入例が少ない＆高価なので、これも現状実現可能性が低いか
入口に置くのは、PINコードみたいなの（前のロッカー番号）をテンキー式で入力して入室するとかが楽かな？
