### ISSUE TITLE
【ホーム画面】入退室処理のAPIにResponseを定義する

### ISSUE THREAD

**Issue by kabigon-1015** [ISDL-dev/ISDL-Sentinel#32]
# 目的/背景

- 入退室処理の状況をfrontendで管理する必要があるが、OpenAPIのスキーマにResponseが存在しない

# 前提条件

- なし
 
# 内容（やること）

- OpenAPIにスキーマを定義する
- APIを再度生成
 
# 完了条件

- [ ] /statusのPUTメソッドにuserIdと更新後のstatusを持つResponseが定義されていること
 
# 参考情報

**Comment by kabigon-1015** [comment]
@hoka-isdl 
スキーマのレビュー漏れすまない！
別のタスク持ってるからこれが完了しないと手が止まるわけじゃないけど、1個タスクに関わるので対応してほしい！

**Comment by hoka-isdl** [comment]
@kabigon-1015 
入退室状況（`status`）は確かにresponseにいるね．
ただAPIは`/sign-in`と`/sign-up`のresponse bodyを更新する方針であってる？？

[自分の解釈]
現状，`/sign-in`と`/sign-up`のresponse bodyに`status`はない．
そのため，`/sign-in`と`/sign-up`のresponse bodyに`status`を入れてログイン時に入退室状況を識別したい．
→ユーザが入室した状態でログアウトし，もう一度ログインした時に`In Room`の状態であることが識別可能

/statusはuserテーブルのstatusを更新するAPI
入室ボタンを押した時にuseContextなどの状態管理に`In Room`の状態を保存する．
退室ボタンを押した時にuseContextなどの状態管理に`Out of Room`の状態を保存する．
これでボタンを押した時の入退室状況は把握できると思う．

**Comment by kabigon-1015** [comment]
@hoka-isdl
`/sign-in`と`/sign-up`は`user_id`を返すだけで問題なさそうかな
homeに遷移した瞬間`users/{user_id}`を呼ぶからstatusはそこから取れそう

細かいけど、useContextに任せると例えばネットワークエラーとかでAPIが正常終了しなかった場合
DBにある`status`とuseContextにある`status`に相違が出てしまうことが考えられるので
Responseを定義しておくとそれが防げるのかなと思った！

**Comment by hoka-isdl** [comment]
了解！(￣^￣)ゞ
確かにネットワークエラーになった場合に相違が起きてしまうね．
`PUT /status`のresponseで`status`を返すようにするね
