### ISSUE TITLE
LAのAPI設計を行う

### ISSUE THREAD

**Issue by hoka-isdl** [ISDL-dev/ISDL-Sentinel#83]
# 目的/背景

- LAシフトボードページを実装するにあたってapi設計を実施する

# 前提条件

- なし

# 内容（やること）

- NotionにLAシフトボードに関するAPI設計を記入する

# 完了条件

- [ ] NotionにLAシフトボードに関するAPI設計を記入すること

# 参考情報

**Comment by hoka-isdl** [comment]
@kabigon-1015 @akiya125 

# LAのAPI定義
## `GET /lab-asistant-member`
### 概要
LAのメンバーを取得するAPI
Gradeテーブルを学年テーブルに中身を変える．そしてU4に該当するuserを返す
user_nameをpostするときに打ち込んで登録すると文字列バリデーションをしなければならないしエラーの原因になりやすい．
そのためトグル形式で選択する形にするとidでuserを識別し送信できるためエラーが少なくなる．
### Response Body
```
[
  {
    "user_id": "uint64",
    "user_name": "string", 
  },
  {
    ...
  }
]
```

## `GET /lab-asistant/:date` 
### 概要
LAの日程とメンバーを取得するAPI
### Response Body
```
[
  {
    "user_name": "string",
    "shift_date": "string",
  }, 
  {
    ...
  }
]
```

## `POST /lab-asistant`
### 概要
LAの登録を行うAPI
### Request Body
```
[
  {
    "user_id": "uint64",
    "shift_date": "string",
  }, 
  {
    ...
  }
]
```
### Response Body
```
[
  {
    "user_name": "string",
    "shift_date": "string",
  }, 
  {
    ...
  }
]
```

**Comment by kabigon-1015** [comment]
あざます！
`GET /lab-asistant/:date`のdateは月指定で渡す想定かな？
あとGoのRESTAPIの仕様が分からんけど、/lab-asistantがPostとGetで2つあるから、実装のタイミングで良からぬ動作をする可能性も考えたほうがいいかも。何の言語か忘れたけどそういうことがありました。
バグってからそこは対応すればいいので、おれはこれでOK！
